paths:
  dataset: "dataset/data.yaml"
  models: "models"
  calibrations_dir: "assets/calibrations/"
  references_dir: "assets/references/"
  telemetry_dir: "assets/telemetry/"

training:
  batch: 8
  imgsz: 640
  epochs: 50
  model_name: yolo11s.pt

inference:
  conf_threshold: 0.25
  iou_threshold: 0.7
  device: cpu

hardware:
  model_type: yolo11s
